import time
import paramiko
import os

from getpass import getpass

HOST = "192.168.1.20"
USER = "ubnt"

if __name__ == "__main__":
	try:

		client = paramiko.SSHClient()
		client.set_missing_host_key_policy( paramiko.AutoAddPolicy() )



		password = getpass("ingrese clave: ")
		client.connect(HOST, username=USER, password=password)
#ELIMINAMOS SYSTEM.CFG
		stdin, stdout, stderr = client.exec_command( "rm /tmp/system.cfg " )
#CREAMOS SYSTEM.CFG
		stdin, stdout, stderr = client.exec_command( "printf '%s'wpasupplicant.profile.1.network.1.eap.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.psk=password wireless >> /tmp/system.cfg")
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.bssid= >> /tmp/system.cfg")
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.key_mgmt.1.name=WPA-PSK >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.ssid=1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.ssid=ptmtp2 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.ssid=ptmtp3 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.ssid=ptmtp4 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.ssid=ptmtp5 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.pairwise.1.name=CCMP >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.network.1.proto.1.name=RSN >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.profile.1.name=WPA-PSK >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.device.1.profile=WPA-PSK >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.device.1.driver=madwifi >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.device.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.device.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wpasupplicant.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'aaa.1.wpa.psk=inetbariloche22 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'aaa.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'aaa.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.ap= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.scan_list.channels= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.scan_list.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.authmode=1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.wds.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.addmtikie=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.hide_ssid=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.security.type=none >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.ssid=ptmtp1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.ssid=ptmtp2 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.ssid=ptmtp3 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.ssid=ptmtp4 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.ssid=ptmtp5 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.hideindoor.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'wireless.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.cable.loss=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.antenna.gain=13 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.antenna.id=4 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.chanbw=40 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.mcastrate=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.rate.mcs=15 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.rate.auto=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.forbiasauto=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.ack.auto=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.ackdistance=600 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.acktimeout=25 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.countrycode=511 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.cwm.enable=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.cwm.mode=1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.dfs.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.ieee_mode=11naht40 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.mode=managed >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.obey=enabledradio.1.polling=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.polling=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.pollingnoack=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.pollingpri= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.reg_obey=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.subsystemid=0xe0a5 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.1.txpower=23 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.rate_module=atheros >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.countrycode=511 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.countrylicense=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'radio.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'httpd.https.port=443 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'httpd.https.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'httpd.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netmode=router >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'sshd.port=22 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'sshd.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'system.cfg.version=65546 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'system.eirp.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'system.modules.blacklist.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'users.1.name=ubnt >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'users.1.password=$1$EXgLMvdY$rut4c6Rx7.NwMsmfTPvW. >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'users.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'users.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'vlan.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.1.ip=192.168.1.1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.2.ip=8.8.8.8 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.2.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.3.ip= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.3.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.4.ip= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.4.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'resolv.nameserver.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.mtu=1500 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.role=wan >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.autoip.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.hwaddr.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.hwaddr.mac= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.ip=192.168.1.254 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.netmask=255.255.255.0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.promisc=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.1.up=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.devname=eth0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.mtu=1500 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.role=lan >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.autoip.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.hwaddr.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.hwaddr.mac= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.ip6.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.ip6.1.addr= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.ip6.1.netmask=64 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.ip=192.168.9.1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.netmask=255.255.255.0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.up=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.2.promisc=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.mtu=1500 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.role=mlan >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.autoip.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.hwaddr.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.hwaddr.mac= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'netconf.3.up=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'bridge.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpc.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpc.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpc.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpc.1.fallback=192.168.10.1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.portfw.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.masq.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.masq.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.masq.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.dmz.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.mgmt.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.mgmt.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.mgmt.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.upnpd.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'iptables.sys.upnpd.devname= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ppp.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.1.ip=0.0.0.0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.1.netmask=0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.1.gateway=192.168.1.1 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.1.comment= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcp6c.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route6.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route6.1.ip= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route6.1.netmask= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route6.1.gateway= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route6.1.comment= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'route6.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dnsmasq.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dnsmasq.1.devname=eth0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dnsmasq.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.status=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.dns.1.server= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.dns.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.dns.2.server= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.dns.2.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.devname=eth0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.start=192.168.9.2 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.end=192.168.9.3 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.netmask=255.255.255.0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.lease_time=600 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcpd.1.dnsproxy=enabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'upnpd.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'upnpd.devname= >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'dhcp6d.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ip6tables.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ip6tables.sys.mgmt.1.devname=ath0 >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ip6tables.sys.mgmt.1.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ip6tables.sys.mgmt.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ebtables.status=disabled >> /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "printf '%s\n'ebtables.sys.vlan.status=disabled >> /tmp/system.cfg " )
#INSERTAMOS PASSWORD		
		stdin, stdout, stderr = client.exec_command( "sed -i 's/users.1.password=.NwMsmfTPvW./INGRESA AQUI TU HASH/g' /tmp/system.cfg " )
		stdin, stdout, stderr = client.exec_command( "cfgmtd -f /tmp/system.cfg -w ")
		stdin, stdout, stderr = client.exec_command( "cat /tmp/system.cfg")


		time.sleep(5)

		result = stdout.read().decode()

		print(result)

		client.close()


	except paramiko.ssh_exception.AuthenticationException as e:
		print("Autenticacion Fallida")
